domain: longqa_wiki
datasets: assets/example_datasets/*_text_corpus.jsonl
lang: en # en or zh
save_dir: your_dataset_path
llm_api:
  model_name: xxx
  api_base: http://xxx
pipelines:
  aggregate_docs:
    type: iclm # iclm, random
    min_aggregated_tokens: 1600
    max_aggregated_tokens: 3200
  extract_questions: 
    chunk_size: 2048
    max_q: 5
  filter_questions:
    - coreference_resoulution
  generate_answers:
    type: one-by-one
    simplify_answer: true
    score_qa_pairs: false
  calculate_qas_correlation:
    type: bge_embedding
    embedder:
      embedder_name: bge_base15_embedder
      backbone_type: BGE
      init_backbone: BAAI/bge-base-en-v1.5
      flashatt: false
      pool_type: cls
      peft_lora: false
      which_layer: -1
      max_length: 512
      task_prompt: false
      checkpoint_batch_size: -1
      mytryoshka_size: 768
      embedding_norm: false
      embedder_ckpt_path:
      reserved_layers:
      device: cuda
      encode_batch_size: 2048
  aggregate_multihop_qas:
    topk: 3
  eval_multihop_qas:
    score: 2